name: Build & Deploy DJ SRM

on:
  push:
    branches: [ "main" ]   # alleen deploy vanaf de main branch

jobs:
  build-release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bepaal versie uit plugin bestand
        id: version
        run: |
          VERSION=$(grep -i "Version:" dj-song-request-manager.php | head -1 | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Gevonden versie: $VERSION"

      - name: Maak ZIP bestand van plugin
        run: |
          zip -r dj-song-request-manager.zip . \
            -x "*.git*" \
            -x ".github/*" \
            -x "node_modules/*" \
            -x "*.zip"

      - name: Publiceer GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: dj-song-request-manager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy naar server
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.zip
            **/*.md
          log-level: verbose
